image: gcc

build:
  stage: build
  script:
    -  make -f make
    - ./ConverterBetweenRomanAndArabicNumbers 27
    - ./ConverterBetweenRomanAndArabicNumbers XVII
    - ./ConverterBetweenRomanAndArabicNumbers 2999
    - ./ConverterBetweenRomanAndArabicNumbers MMCMXCIX
